### ISSUE TITLE
(idea) Open website in mobile view

### ISSUE THREAD

**Issue by Vingolf** [Soushi-Atsumi/Open-in-Sidebar#1]
#### Add an option to open a website in mobile view.

This could improve your add-on for a website like [Deepl-Translation](https://www.deepl.com/translator)  
that fits much better to the sidebar in mobile view than in desktop view.

You can easily switch the main page of Firefox to mobile view using [Ctrl] + [Shift] + [m],  
but this does not work for the sidebar.

@Soushi-Atsumi you have created a useful add-on and think it has a lot of potential 🚀

Vingolf

**Comment by Soushi-Atsumi** [comment]
Hi, Vingolf.

Features like this are requested many times in Open in SIdebar and [Search in Sidebar](https://github.com/Soushi-Atsumi/Search-in-Sidebar).
However, I cannot implement this feature currently because Mozilla has no longer provided API for opening Responsive Design Mode(mobile view).
In addition, only an owner of a website can decide that a window should display as a mobile view or not. Some websites like Deepl doesn't support a narrow screen, and some websites like GitHub support it. So a page of GitHub is displayed as a mobile view in a sidebar.

Sadly, the only thing we can do currently is waiting.

**Comment by Soushi-Atsumi** [comment]
I have released v4.0.0 which has a feature of changing a user agent and this makes this extension opening a mobile view.
Closed by [v4.0.0](https://github.com/Soushi-Atsumi/Open-in-Sidebar/releases/tag/v4.0.0).
