### ISSUE TITLE
Sidebar page URL?

### ISSUE THREAD

**Issue by Octur1s** [Soushi-Atsumi/Open-in-Sidebar#14]
Hello, I was wondering if it is possible to access the url of the page that is currently open the sidebar.
I assume that it must be stored or cached temporarily, but is there a way to view, extract or utilize it, perhaps with a js script?
My thought is that it would be convenient to have a header in the sidebar that shows the url, so that it could be reopened in a normal tab.

Thank you

**Comment by Soushi-Atsumi** [comment]
Hi, Octur1s

Yes, accessing the url of the sidebar is possible by using [a content script](https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/Content_scripts). However, the design of the sidebar cannot be changed because the sidebar is one of Firefox but not the extension.
In conclusion, the extension can know the url of the sidebar but it cannot be displayed.
An extension that copy the url of the current page may help you.

**Comment by Octur1s** [comment]
Thank you, I've found an extension that allows me to open the current page in the sidebar in a normal tab. 

![Animation2](https://github.com/Soushi-Atsumi/Open-in-Sidebar/assets/118348776/413947f8-6eb9-4aea-8994-81286bd766cd)

I may just use this in combination with your extension. If you could consider adding this functionality to your own that would be great!

Thanks again

**Comment by Soushi-Atsumi** [comment]
Thanks for the example and telling the extension. This extension is very interesting.
I will add the feature like you told.
