### ISSUE TITLE
[Feature-Request] Options related to toogle action

### ISSUE THREAD

**Issue by logusergithub** [Soushi-Atsumi/Open-in-Sidebar#17]
Hi,
thanks for this nice extension: full of features and it doesn't require unnecessary permissions. Here the requests:

1.  I don't know if this is feasible, but for users who perhaps have set min and max values for the sidebar, is it possible an option to recall them via the toogle action? Or alternatively a option could be put directly into the extension to set custom values (open to max value, close to min value).
```
#Sidebar-Box {
Max-Width. 930px !Important;
Min-Width. 237px !Important;
}
```

2. I don't know if it's useful for all bar opening behaviors, at the moment I think I'm comfortable with 'Tab' and the request may be limited to this one: an option that allows you to reset the state and restore the bookmarks tab (or maybe give a choice since there are also vertical tabs) when you close the sidebar with the 'Open-in-Sidebar' icon.

To be honest, I don't actually see them as significant options in general, but since to level the sidebar with the main window I removed '#sidebar-header' (and I use only the bookmark tab), I would then save a couple of clicks and  and wouldn't even waste time adjusting the max width of the bar.

Out of the topic if you are interested a draft of the Italian translation is available, but due to my limitations I still have to understand some points. Feel free when you have time to explain them to me:

1. indexHTMLHeading1
Right click selected characters of a URL? It seems to me that if I select the full text of a URL (which not to link) I can open it in the sidebar. Different is the case if I select a generic text on the page: I don't open the source of the selection as with Firefox but get the warning of an invalid URL. Right?

2. optionsUserAgentHTMLCaution
The only thing I understood is that if I select the user agent with the extension this affects all the open sidebars. And it doesn't change if in case I set another user agent on the main window with a dedicated extension. Did I miss anything else?

3. placement(All\Tab\Window)Caution
'can be overwritten...'? If I start using 'All' setting and then open a sidebar and select 'Windows' all sidebars opened with 'All' change at once 'Windows'. For 'All' setting, it also seems to me that I cannot use it if I have already opened with 'Windows' and 'Tab' ways before (I suppose because precisely he cannot overwrite them). These last two coexist well, maybe there would also be another option about putting in the menu of the icon on the toolbar the selection of these opening behaviors (if starting with 'Windows' setting, then opening a new tab and the options to use 'Tab' --> all 'Windows' switches to the options page').

**Comment by Soushi-Atsumi** [comment]
Hi, logusergithub

> 1. I don't know if this is feasible, but for users who perhaps have set min and max values for the sidebar, is it possible an option to recall them via the toogle action?

I think it is impossible but you may call standard APIs like document.body.clientWidth to get the width.
This is not a question for this extension but for the standard feature of Firefox, so I haven't investigated this question deeply.
> Or alternatively a option could be put directly into the extension to set custom values (open to max value, close to min value).

I think this is impossible also. WebExtensions API don't have a strong permission.
> Out of the topic if you are interested a draft of the Italian translation is available, but due to my limitations I still have to understand some points. Feel free when you have time to explain them to me:

A contribution is always welcome. Please feel free to bring your translation.
> indexHTMLHeading1
Right click selected characters of a URL? It seems to me that if I select the full text of a URL (which not to link) I can open it in the sidebar. Different is the case if I select a generic text on the page: I don't open the source of the selection as with Firefox but get the warning of an invalid URL. Right?

Yes. So it can open a link which is not tagged with [a](https://developer.mozilla.org/ja/docs/Web/HTML/Element/a).
> optionsUserAgentHTMLCaution
The only thing I understood is that if I select the user agent with the extension this affects all the open sidebars. And it doesn't change if in case I set another user agent on the main window with a dedicated extension. Did I miss anything else?

Changing an user-agent with this extension affects all pages (like the sidebar, the popup and so on) provided by an extension (including other extension). If other extension tries to change the user-agent too, Firefox determines which user-agents should be used.
> placement(All\Tab\Window)Caution
'can be overwritten...'? If I start using 'All' setting and then open a sidebar and select 'Windows' all sidebars opened with 'All' change at once 'Windows'. For 'All' setting, it also seems to me that I cannot use it if I have already opened with 'Windows' and 'Tab' ways before (I suppose because precisely he cannot overwrite them).

Yes. You can read details about it on [this document](https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/sidebarAction/setPanel).
> These last two coexist well, maybe there would also be another option about putting in the menu of the icon on the toolbar the selection of these opening behaviors (if starting with 'Windows' setting, then opening a new tab and the options to use 'Tab' --> all 'Windows' switches to the options page').

I don't think users need the feature like this.

**Comment by logusergithub** [comment]
Hi,
thanks for the explanation. I always forget what is the correct procedure to submit a change, I hope I did everything right.

Sadly, the fact that the extensions are limited compared to before I remember it every time while using Tile Tabs one of my favorite extensions.

Anyway if it can be useful to other users as well in these days I have seen that by making a small change to <a href="https://github.com/garywill/sidebar-switch">this</a> very useful script (`line 30 toggle("viewBookmarksSidebar")`) and using it in combination with <a href="https://github.com/aminought/firefox-sidebar-width">this</a> other one, I can more or less achieve the desired behavior to open in the sidebar. Maybe it can be done better but I am a beginners user.
