### ISSUE TITLE
Ideia: Makes the Sidebar float like in Opera/Vivaldi?

### ISSUE THREAD

**Issue by ethpsantos** [Soushi-Atsumi/Open-in-Sidebar#2]
It just an ideia.
To have an option to make the sidebar floating over the page with an auto-close when you have action outside the sidebar page just like Opera/Vivaldi is a great add.
The way it is not making the page content go to left to open the sidebar is not useful imo.

**Comment by Soushi-Atsumi** [comment]
Hi, ethpsantos

Thanks for your idea. I don't use Opera/Vivaldi so I checked the feature.
https://help.opera.com/en/latest/features/#operaPlayer
I thought that this is a cool feature but I have seen a thing like this... oh, it is a popup of Firefox. However, the popup cannot be long because of a specification of Firefox. It has a scrollbar instead of being long.
In conclusion, an extension cannot make a sidebar floating because the sidebar itself needs to be modified. An extension can modify only an internal content of a sidebar.
I think only developers of Firefox can add this feature.

**Comment by ethpsantos** [comment]
I understand.
Thanks for the reply.
