### ISSUE TITLE
Show URL of the opened page

### ISSUE THREAD

**Issue by SanmayJoshi** [Soushi-Atsumi/Open-in-Sidebar#20]
Great extension! I was wondering if the below stated was possible.

## Desired feature
Providing an option to the user to view an address bar at top of the sidebar. The address bar should preferably:
* Show the URL of the page opened in the sidebar
* Allow the user to copy the URL address

---

**Comment by Soushi-Atsumi** [comment]
Hi, SanmayJoshi

Currently, there are two ways to get a location of a page.

- Receive [menus.onShown Event](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/onShown)
- Run [tabs API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs)

The first way need to be interacted the sidebar by a user before it displays url, so it is hard to adopt.
The second way may conflict other extension which uses a special page (like the sidebar and the popup) because the APIs cannot identify the page is own or not.
In addition, a developer cannot change the design of the sidebar. iframe may resolve this problem but some websites cannot work with it.
If you have installed an extension which copy the URL address of current page with right click, you can use it instead of this requested feature.

**Comment by SanmayJoshi** [comment]
Hi,
The primary use case that I had in mind for this feature is when the user has spent some time browsing in the sidebar and now wants to get the URL of the page s/he is on.

I have no experience in Firefox extensions, so please excuse me if I am not making much sense, but I would love it if something like the below is possible (probably with the `menus.onShown`):
1. There is always a bar at the top of the sidebar (similar to the URL bar in browsers) that says click to view URL
   * The user should probably have the option to enable/disable this feature and the constantly appearing URL bar on top
2. When the user clicks the top bar, the URL of the 'current page loaded in the sidebar' is shown in the top bar along with a button to copy the URL.

**Comment by Soushi-Atsumi** [comment]
> The primary use case that I had in mind for this feature is when the user has spent some time browsing in the sidebar and now wants to get the URL of the page s/he is on.

You can copy the url of the page by using other extension (like: [copy-frame-or-page-url](https://addons.mozilla.org/firefox/addon/copy-frame-or-page-url)). So I don't think that you need the url bar to realize this.

> * There is always a bar at the top of the sidebar (similar to the URL bar in browsers) that says click to view URL
>   
>   * The user should probably have the option to enable/disable this feature and the constantly appearing URL bar on top
> 
> * When the user clicks the top bar, the URL of the 'current page loaded in the sidebar' is shown in the top bar along with a button to copy the URL.

I think you should use a window instead of the sidebar.
