### ISSUE TITLE
suggestion: add option to enable ask user-agent

### ISSUE THREAD

**Issue by u-Sir** [Soushi-Atsumi/Open-in-Sidebar#6]
![图片](https://user-images.githubusercontent.com/93647031/227725953-bab93b9f-c09d-4774-a3f8-f5b035e84042.png)
add `ask` option for `user agent`, just like `protocol` and `target`

**Comment by Soushi-Atsumi** [comment]
I think this feature is not necessary for this add-on. Because changing User-Agent is not the main feature.
By the way, you can use custom User-Agent in the sidebar by using other extension which changes User-Agent.

**Comment by u-Sir** [comment]
> Hi, u-Sir
> 
> I think this feature is not necessary for this add-on. Because changing User-Agent is not the main feature. By the way, you can use custom User-Agent in the sidebar by using other extension which changes User-Agent.

No, some websites have a better experience in 'PC mode' in sidebar, and the others will be better in 'Mobile mode', so it would be better to add an option to select UA.

**Comment by Soushi-Atsumi** [comment]
Well, I misunderstood [your comment](https://github.com/Soushi-Atsumi/Open-in-Sidebar/issues/6#issue-1640552787). Surely it is better to be implemented.

**Comment by Soushi-Atsumi** [comment]
This feature makes a user confused. Because the sidebar can be opened in a specific tab or a specific window but the option of User-Agent is always global.
For instance, a user expects that the first sidebar which is opened with Default always displays in PC mode but it can be Mobile mode if a user open the second sidebar which is opened with FirefoxOS.
